package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/fathdemr/nexus-interview/docs" // generated by `swag init` (make swag)
	"github.com/fathdemr/nexus-interview/internal/admin"
	"github.com/fathdemr/nexus-interview/internal/auth"
	"github.com/fathdemr/nexus-interview/internal/candidate"
	"github.com/fathdemr/nexus-interview/internal/question"
	"github.com/fathdemr/nexus-interview/pkg/cache"
	"github.com/fathdemr/nexus-interview/pkg/config"
	"github.com/fathdemr/nexus-interview/pkg/database"
	"github.com/fathdemr/nexus-interview/pkg/logger"
	"github.com/fathdemr/nexus-interview/pkg/middleware"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("load config: %v", err)
	}

	if err := logger.Init(cfg.Server.Mode); err != nil {
		log.Fatalf("init logger: %v", err)
	}
	defer logger.Sync()

	db, err := database.Connect(cfg.Database.DSN(), cfg.Server.Mode == "debug")
	if err != nil {
		logger.S().Fatalf("connect database: %v", err)
	}
	if err := database.Migrate(db); err != nil {
		logger.S().Fatalf("migrate database: %v", err)
	}

	redisClient, err := cache.NewClient(cfg.Redis.Addr, cfg.Redis.Pass, cfg.Redis.DB, cfg.Redis.TLS)
	if err != nil {
		logger.S().Fatalf("connect redis: %v", err)
	}
	cacheService := cache.New(redisClient)

	authService := auth.NewService(
		cfg.JWT.PrivateKey,
		cfg.JWT.PublicKey,
		cfg.JWT.AccessTokenExpirationMinutes,
		cfg.JWT.RefreshTokenExpirationDays,
		cacheService,
	)

	authHandlerCfg := auth.HandlerConfig{
		CookieDomain:               cfg.JWT.CookieDomain,
		CookieSecure:               cfg.JWT.CookieSecure,
		RefreshTokenExpirationDays: cfg.JWT.RefreshTokenExpirationDays,
	}

	candidateRepo := candidate.NewRepository(db)
	questionRepo := question.NewRepository(db)

	adminService := admin.NewService()
	candidateService := candidate.NewService(candidateRepo)
	questionService := question.NewService(questionRepo)

	gin.SetMode(cfg.Server.Mode)
	router := gin.New()
	router.Use(middleware.Recovery())
	router.Use(middleware.RequestLogger())

	authHandler := auth.NewHandler(authService, authHandlerCfg)

	// Swagger UI — served outside /api/v1 so it is never behind auth middleware.
	router.GET("/swagger/*any", gin.BasicAuth(
		gin.Accounts{cfg.Swagger.Username: cfg.Swagger.Password}),
		ginSwagger.WrapHandler(swaggerFiles.Handler),
	)

	public := router.Group("/api/v1")
	{
		public.GET("/healthcheck", publicHealthcheck)
		authHandler.RegisterRoutes(public.Group("/auth"))
	}

	protected := router.Group("/api/v1")
	protected.Use(middleware.CheckToken(authService))
	{
		authHandler.RegisterProtectedRoutes(protected.Group("/auth"))
		admin.NewHandler(adminService).RegisterRoutes(protected.Group("/admin"))
		candidate.NewHandler(candidateService).RegisterRoutes(protected.Group("/candidates"))
		question.NewHandler(questionService).RegisterRoutes(protected.Group("/questions"))
	}

	addr := fmt.Sprintf(":%s", cfg.Server.Port)
	logger.S().Infof("server starting on %s (mode: %s)", addr, cfg.Server.Mode)

	server := &http.Server{
		Addr:              addr,
		Handler:           router,
		ReadHeaderTimeout: 10 * time.Second,
		WriteTimeout:      60 * time.Second,
	}

	go func() {
		if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			logger.S().Errorf("server error: %v", err)
			os.Exit(1)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	logger.S().Info("shutting down server...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := server.Shutdown(shutdownCtx); err != nil {
		logger.S().Errorf("graceful shutdown failed: %v", err)
	}

	// Close DB connection pool
	if sqlDB, err := db.DB(); err == nil {
		if err := sqlDB.Close(); err != nil {
			logger.S().Errorf("close database: %v", err)
		}
	}

	// Close Redis connection pool
	if err := redisClient.Close(); err != nil {
		logger.S().Errorf("close redis: %v", err)
	}

	logger.S().Info("server stopped")
}

// publicHealthcheck reports process liveness without touching any dependency.
//
// @Summary      Liveness probe
// @Description  Returns 200 as long as the HTTP server is up. Does not check database or Redis; use /admin/healthcheck for that.
// @Tags         System
// @Produce      json
// @Success      200  {object}  map[string]string  "status: ok"
// @Router       /healthcheck [get]
func publicHealthcheck(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "ok"})
}
